### ISSUE TITLE
Help with modifying code to comply with different payload

### ISSUE THREAD

**Issue by MetroFosterRep** [dvci/health-cards-walkthrough#7]
[health-cards-walkthrough-main.zip](https://github.com/dvci/health-cards-walkthrough/files/7507280/health-cards-walkthrough-main.zip)
Hey, I have been trying to modify the Smart Health Card to comply with with the FHIR Bundle for British Columbia. I am struggling with the verification process for my QR codes, back and forth. Any help would be much appreciated.

**Comment by TRM13** [comment]
So are you starting with a known working QRCode? I'm on Linux but the tools are available for other platforms.
If you use QtQR, or some other tool, to get the "shc:/+jws" part by clicking edit. Copy it all except the "shc:/" part.
You can either run the code from a python script or just edit the Jupyter Lab and change the line:
const qrCodeData = 'shc:/' + numericJWS
becomes
const qrCodeData = 'shc:/' + 'Your long string of numbers goes here'
Then continue running the Jupyter Lab code blocks and it will generate the QRCode.

To change it you would need the signing key that they use. That or just run billions of attempts to see if you can get lucky with a brute force approach.

**Comment by radamson** [comment]
As @TRM13 mentioned, if you're working with an already signed SMART Health Card then you won't be able to modify the payload without compromising the data integrity provided by the digital signature. In order to restore data integrity the payload would need to be signed again after modification.

If you have access to the secret key used for signing the SMART Health Card and are primarily concerned with having the FHIR Bundle confirm to the FHIR profiles then there are some other tools that can help.

The [FHIR IG has a Validation section](https://build.fhir.org/ig/HL7/fhir-shc-vaccination-ig/profiles.html#validation) which provides instructions for how to validate that the FHIR bundle conforms to the proper profile (you should test against `http://hl7.org/fhir/uv/shc-vaccination/StructureDefinition/shc-vaccination-bundle-dm` profile)

e.g.

```shell
java -jar path/to/validator_cli.jar -version 4.0.1 \
-ig path/to/package.tgz \
-profile http://hl7.org/fhir/uv/shc-vaccination/StructureDefinition/shc-vaccination-bundle-dm \
path/to/immunization-bundle.json
```

This validator will provide error and warning messages highlighting what issues are causing non-conformance. Once you have a conforming payload then you can verify that you've constructed the QR code correctly with the [SMART Health Cards Dev Tools](https://github.com/smart-on-fhir/health-cards-dev-tools)

**Comment by hotcobra** [comment]
This code assumes you're creating the first SMART CARD for your province.  In a production environment you would read in your private key from disk, and then create the JWS. I have it working fine in Jupyter notebook but   struggling to get this working using Node.JS or Chrome

**Comment by radamson** [comment]
Closing this issue since an answer to the original question was provided. Feel free to reopen if you'd like to discuss further or have additional details about the issue that you'd like to share.
